variables:
  AUTHORIZED_KEY: ${AUTHORIZED_KEY}
  TF_ROOT: ${CI_PROJECT_DIR}/infra
  TF_IN_AUTOMATION: "true"
  TF_VAR_service_account_key_file: ${TF_ROOT}/authorized_key.json
  TF_VAR_zone: ${TF_VAR_zone}
  TF_VAR_cloud_id: ${TF_VAR_cloud_id}
  OPERATION:
    description: "Select CI/CD-operation"
    value: "terraform"
    options:
      - "terraform"
      - "ansible"
      - "k8s"

stages:
  - tests
  - plan
  - apply
  - terratest
  - ansible_deploy
  - destroy
  - build
  - package

default:
  before_script:
    - cd ${TF_ROOT}
    - echo ${AUTHORIZED_KEY} | base64 -d > ./authorized_key.json

terraform-plan-job:
  stage: plan
  script:
    - echo "Running Terraform plan..."
    - terraform init 
    - terraform plan
  rules:
    - if: $OPERATION == "terraform"
      when: always 

terraform-apply-job:
  stage: apply
  script:
    - echo "Applying Terraform..."
    - terraform init
    - terraform apply -auto-approve
  rules:
    - if: $OPERATION == "terraform"
      when: manual

terraform-destroy-job:
  stage: destroy
  script:
    - echo "Destroying Terraform infrastructure..."
    - terraform destroy -auto-approve
  rules:
    - if: $OPERATION == "terraform"
      when: manual

# Выполнение тестов checkov
#security_scan:

# Выполнение тестов terratest
#terratest:


# Деплой ansible-playbook
#ansible-deploy:

# Сборка и пуш Docker-образов в DockerHub
#build-and-push-images:

# Упаковка и пуш Helm-чарта в Nexus
#package-helm-chart:
