variables:
  OPERATION:
    description: Select CI/CD-operation to perform
    value: terraform
    options:
      - terraform
      - ansible
      - k8s
  TF_ROOT: ${CI_PROJECT_DIR}/infra
  TF_IN_AUTOMATION: "true"

stages:
  - tests
  - plan
  - apply
  - terratest
  - ansible_deploy
  - destroy
  - build
  - package

default:
  before_script:
    - cd ${TF_ROOT}
    - echo ${AUTHORIZED_KEY} | base64 -d > ${TF_ROOT}/authorized_key.json
    - export TF_VAR_service_account_key_file=${TF_ROOT}/authorized_key.json

scan-terraform-files:
  stage: tests
  image: bridgecrew/checkov:latest
  script:
    - checkov -d . --compact --quiet
  rules:
    - if: $OPERATION == "terraform"
      when: always
  allow_failure: true

plan-terraform-changes:
  stage: plan
  script:
    - terraform init 
    - terraform plan
  rules:
    - if: $OPERATION == "terraform"
      when: always 

apply-terraform-changes:
  stage: apply
  script:
    - terraform init
    - terraform apply -auto-approve
  rules:
    - if: $OPERATION == "terraform"
      when: manual

destroy-terraform-infrastructure:
  stage: destroy
  script:
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: $OPERATION == "terraform"
      when: manual

run-terraform-tests:
  stage: terratest
  script:
    - cd test
    - go mod init terratest
    - go mod tidy
    - go test -v
  needs:
    - job: apply-terraform-changes
      optional: true
  rules:
    - when: manual
      if: $OPERATION == "terraform"
  allow_failure: false

deploy-with-ansible:
  stage: ansible_deploy
  image: williamyeh/ansible:ubuntu18.04
  script:
    - mkdir -p ~/.ssh
    - echo ${SSH_PRIVATE_KEY} | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - terraform init
    - cd ${CI_PROJECT_DIR}/ansible
    - ansible-playbook vault-playbook.yaml
  rules:
    - if: $OPERATION == "ansible"
      when: always

build-and-push-images:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build --build-arg VERSION=$CI_COMMIT_SHA --push -t $DOCKER_USER/sausage-backend:latest ./backend/
    - docker build --push -t $DOCKER_USER/sausage-frontend:latest ./frontend/
    - docker build --push -t $DOCKER_USER/sausage-backend-report:latest ./backend-report/
  rules:
    - if: $OPERATION == "k8s"
      when: always

# Упаковка и пуш Helm-чарта в Nexus
#package-helm-chart:
